const Map<String, double> features = const {
  'Total Fwd Packets': 1,
  'Total Backward Packets': 1,
  'Total Length of Fwd Packets': 0.0,
  'Total Length of Bwd Packets': 0.0,
  'Fwd Packet Length Max': 0.0,
  'Fwd Packet Length Min': 0.0,
  'Fwd Packet Length Mean': 0.0,
  'Fwd Packet Length Std': 0.0,
  'Bwd Packet Length Max': 0.0,
  'Bwd Packet Length Min': 0.0,
  'Bwd Packet Length Mean': 0.0,
  'Bwd Packet Length Std': 0.0,
  'Flow Bytes/s': 0.0,
  'Flow Packets/s': 53.7619956453,
  'Flow IAT Mean': 37201.0,
  'Flow IAT Std': 0.0,
  'Flow IAT Max': 37201.0,
  'Flow IAT Min': 37201.0,
  'Fwd IAT Total': 0.0,
  'Fwd IAT Mean': 0.0,
  'Fwd IAT Std': 0.0,
  'Fwd IAT Max': 0.0,
  'Fwd IAT Min': 0.0,
  'Bwd IAT Total': 0.0,
  'Bwd IAT Mean': 0.0,
  'Bwd IAT Std': 0.0,
  'Bwd IAT Max': 0.0,
  'Bwd IAT Min': 0.0,
  'Fwd PSH Flags': 0,
  'Bwd PSH Flags': 0,
  'Fwd URG Flags': 0,
  'Bwd URG Flags': 0,
  'Fwd Header Length': 32,
  'Bwd Header Length': 32,
  'Fwd Packets/s': 26.8809978226,
  'Bwd Packets/s': 26.8809978226,
  'Min Packet Length': 0.0,
  'Max Packet Length': 0.0,
  'Packet Length Mean': 0.0,
  'Packet Length Std': 0.0,
  'Packet Length Variance': 0.0,
  'FIN Flag Count': 0,
  'SYN Flag Count': 0,
  'RST Flag Count': 0,
  'PSH Flag Count': 0,
  'ACK Flag Count': 1,
  'URG Flag Count': 1,
  'CWE Flag Count': 0,
  'ECE Flag Count': 0,
  'Down/Up Ratio': 1.0,
  'Average Packet Size': 0.0,
  'Avg Fwd Segment Size': 0.0,
  'Avg Bwd Segment Size': 0.0,
  'Fwd Header Length.1': 32,
  'Fwd Avg Bytes/Bulk': 0,
  'Fwd Avg Packets/Bulk': 0,
  'Fwd Avg Bulk Rate': 0,
  'Bwd Avg Bytes/Bulk': 0,
  'Bwd Avg Packets/Bulk': 0,
  'Bwd Avg Bulk Rate': 0,
  'Subflow Fwd Packets': 1,
  'Subflow Fwd Bytes': 0,
  'Subflow Bwd Packets': 1,
  'Subflow Bwd Bytes': 0,
  'Init_Win_bytes_forward': 1724,
  'Init_Win_bytes_backward': 404,
  'act_data_pkt_fwd': 0,
  'min_seg_size_forward': 32,
  'Active Mean': 0.0,
  'Active Std': 0.0,
  'Active Max': 0.0,
  'Active Min': 0.0,
  'Idle Mean': 0.0,
  'Idle Std': 0.0,
  'Idle Max': 0.0,
  'Idle Min': 0.0
};
